site/exhibitionInferenceSite/exhibitionInferenceApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "exhibitionInferenceApp_ns"
urlpatterns = [
    path("", views.index, name="index"),
    path("visualisation/", views.visualisationDefault,
         name="visualisation-default"),
    path("visualisation/all/", views.visualisationAll, name="visualisation-all"),
    path("visualisation/startEndQuery/",
         views.visualisationStartEndQuery, name="visualisation-start-end-query"),
    path("visualisation/start/<str:startTime>/end/<str:endTime>/",
         views.visualisationStartEnd, name="visualisation-start-end"),
    path("visualisation/session/<int:sessionId>/",
         views.visualisationSession, name="visualisation-session"),
    path("data", views.dataDefault, name="data-default"),
    path("submit/", views.submitReading, name="submit"),
    path(
        "frontdesk/devices/",
        views.frontdeskDeviceSelect,
        name="frontdesk-device-select"
    ),
    path(
        "frontdesk/devices/<str:hardwareId>",
        views.frontdeskDeviceManage,
        name="frontdesk-device-manage"
    ),
    path(
        "frontdesk/devices/<str:hardwareId>/submit",
        views.frontdeskDeviceManageSubmit,
        name="frontdesk-device-manage-submit"
    ),
    path(
        "frontdesk/sessions/",
        views.frontdeskSessionSelect,
        name="frontdesk-session-select"
    ),
    path(
        "frontdesk/sessions/<int:sessionId>",
        views.frontdeskSessionManage,
        name="frontdesk-session-manage"
    ),
    path(
        "frontdesk/sessions/<int:sessionId>/submit",
        views.frontdeskSessionManageSubmit,
        name="frontdesk-session-manage-submit"
    ),
    path("login/", views.login, name="login"),
    path("login/submit/", views.loginPost, name="login-submit"),
    path("logout/", views.logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site/exhibitionInferenceSite/exhibitionInferenceSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('exhibitionInferenceApp.urls')),
    path('admin/', admin.site.urls),
]

site/exhibitionInferenceSite/exhibitionInferenceApp/models.py
from django.db import models
from django.db.models import F, Q
from django.contrib import admin


class Metadata(models.Model):
    """
    Project-wide settings
    """
    key = models.CharField(max_length=100, primary_key=True)
    value = models.CharField(max_length=200)

    # Key-value pair
    def __str__(self):
        return f"{self.key}={self.value}"


class Session(models.Model):
    """
    Each record represents a session (1 person holding 1 tag walking around museum from start to end).
    """
    device = models.ForeignKey(
        'Device', on_delete=models.CASCADE, db_column='hardwareId')
    metadata = models.CharField(max_length=1000, null=True, blank=True)
    # these are redundant, but optimise a common query
    startTime = models.DateTimeField('start time')
    endTime = models.DateTimeField('end time', null=True, blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                # startTime <= endTime; https://docs.djangoproject.com/en/4.0/topics/db/queries/#filters-can-reference-fields-on-the-model
                check=Q(startTime__lte=F("endTime")),
                name="session_startTime_before_endTime_check"
            )
        ]

    @admin.display(description="Session ID")
    def admin_session_id(self) -> int:
        """
        Used only in admin.py
        """
        return self.pk

    def session_has_ended(self) -> bool:
        return self.endTime is not None

    def __str__(self):
        if self.metadata:
            return f"{self.device}({self.startTime}-{self.endTime}): {(self.metadata[:10] + '...') if len(self.metadata) > 10 else self.metadata}"
        else:
            return f"{self.device}({self.startTime}-{self.endTime})"

    def toJson(self) -> dict:
        return {
            "pk": self.pk,
            "startTime": self.startTime.isoformat(),
            "endTime": None if self.endTime is None else self.endTime.isoformat(),
            "metadata": self.metadata,
        }


class Reading(models.Model):
    """
    Each record is a coordinate of a tag (of a session) at some instant in time.
    """
    x = models.FloatField()
    y = models.FloatField()
    z = models.FloatField()
    t = models.DateTimeField('timestamp')
    # if we delete session, then delete reading
    session = models.ForeignKey('Session', on_delete=models.CASCADE)
    quality = models.IntegerField()

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(quality__gte=0) & Q(quality__lte=100),
                name="quality_bounds_check"
            ),
            models.UniqueConstraint(
                fields=["session", "t"], name="idempotency_check"),
        ]
        permissions = [
            ("visualise_reading", "Can view visualisation pages")
        ]

    def __str__(self):
        return f"({self.x}, {self.y}, {self.z}) at t={self.t}"

    def toJson(self) -> dict:
        return {
            "x": self.x,
            "y": self.y,
            "z": self.z,
            "t": self.t.isoformat(),
            "session": self.session.toJson(),
            "quality": self.quality
        }


class Device(models.Model):
    """
    Each record represents a physical device, and the frontdesk officer can key in data related to the session
    (E.g. whether the person is carrying a audioguide)
    """
    hardwareId = models.CharField(max_length=200, primary_key=True)
    # store metadata with device until session starts
    metadata = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        if self.metadata:
            return f"{self.hardwareId}: {(self.metadata[:10] + '...') if len(self.metadata) > 10 else self.metadata}"
        else:
            return self.hardwareId

    def toJson(self) -> dict:
        return {
            "id": self.pk,
            "hardwareId": self.hardwareId,
            "metadata": self.metadata,
        }

site/exhibitionInferenceSite/exhibitionInferenceApp/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login as authLogin, logout as authLogout
from django.contrib.auth.decorators import login_required, permission_required
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseBadRequest, Http404, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.dateparse import parse_datetime
from django.utils.timezone import make_aware
from django.views.decorators.csrf import csrf_exempt
import json
from typing import List, Optional
from urllib.parse import urlparse, parse_qs

from . import utils
from .models import Device, Reading, Session


#########
# INDEX #
#########

class ReadingEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, Reading):
            return o.toJson()
        return json.JSONEncoder.default(self, o)


def index(req: WSGIRequest) -> HttpResponse:
    if req.method != "GET":
        raise Http404("Must make a GET request!")

    if not req.user.is_authenticated:
        # If not logged in, show "Nothing to show" page
        return render(req, "exhibitionInferenceApp/unauthenticated.html", context={})
    return render(req, "exhibitionInferenceApp/index.html", context={})


#################
# VISUALISATION #
#################

@login_required(login_url=reverse_lazy("exhibitionInferenceApp_ns:login"))
@permission_required(
    "exhibitionInferenceApp.visualise_reading",
    raise_exception=True
)
def visualisationDefault(req: WSGIRequest) -> HttpResponse:
    if req.method != "GET":
        raise Http404("Must make a GET request!")

    sessions = utils.getAllSessionsReverseOrder()
    paginator = Paginator(sessions, 25)  # Show 25 sessions per page
    page_number = req.GET.get("page")
    sessionsPage = paginator.get_page(page_number)
    return render(req, "exhibitionInferenceApp/visualisationDefault.html", context={
        "sessionsPage": sessionsPage,
        "totalNumberOfSessions": len(sessions)
    })


@login_required(login_url=reverse_lazy("exhibitionInferenceApp_ns:login"))
@permission_required(
    "exhibitionInferenceApp.visualise_reading",
    raise_exception=True
)
def visualisationAll(req: WSGIRequest) -> HttpResponse:
    if req.method != "GET":
        raise Http404("Must make a GET request!")

    readings: List[Reading] = utils.getAllReadings()
    return render(req, "exhibitionInferenceApp/visualisation.html", context={
        "data": json.dumps(readings, cls=ReadingEncoder),
        "allSessionCount": len(Session.objects.all()),
        "readingsCount": len(readings)
    })


@login_required(login_url=reverse_lazy("exhibitionInferenceApp_ns:login"))
@permission_required(
    "exhibitionInferenceApp.visualise_reading",
    raise_exception=True
)
def visualisationStartEndQuery(req: WSGIRequest) -> HttpResponse:
    if req.method != "POST":
        raise Http404("Must make a POST request!")
    errors = []
    if parse_datetime(req.POST["start"]) is None:
        errors.append("Invalid start datetime")
    if parse_datetime(req.POST["end"]) is None:
        errors.append("Invalid end datetime")
    if len(errors) > 0:
        messages.error(req, f"{', '.join(errors)}.")
        return HttpResponseRedirect(reverse("exhibitionInferenceApp_ns:visualisation-default"))
    return HttpResponseRedirect(reverse(
        "exhibitionInferenceApp_ns:visualisation-start-end",
        args=(req.POST["start"], req.POST["end"])
    ))


@login_required(login_url=reverse_lazy("exhibitionInferenceApp_ns:login"))
@permission_required(
    "exhibitionInferenceApp.visualise_reading",
    raise_exception=True
)
def visualisationStartEnd(req: WSGIRequest, startTime: str, endTime: str) -> HttpResponse:
    if req.method != "GET":
        raise Http404("Must make a GET request!")

    startDateTime = parse_datetime(startTime)
    endDateTime = parse_datetime(endTime)
    if startDateTime is None or endDateTime is None:
        # severely malformed datetime strings provided
        return HttpResponseBadRequest()

    readings: List[Reading] = utils.getReadingsBetween(
        startTime=startTime, endTime=endTime)
    return render(req, "exhibitionInferenceApp/visualisation.html", context={
        "data": json.dumps(readings, cls=ReadingEncoder),
        "startDateTime": startDateTime,
        "endDateTime": endDateTime,
        "readingsCount": len(readings)
    })


@login_required(login_url=reverse_lazy("exhibitionInferenceApp_ns:login"))
@permission_required(
    "exhibitionInferenceApp.visualise_reading",
    raise_exception=True
)
def visualisationSession(req: WSGIRequest, sessionId: int) -> HttpResponse:
    if req.method != "GET":
        raise Http404("Must make a GET request!")

    s = get_object_or_404(Session, pk=sessionId)
    readings: List[Reading] = utils.getSessionReadings(sessionId=sessionId)
    return render(req, "exhibitionInferenceApp/visualisation.html", context={
        "data": json.dumps(readings, cls=ReadingEncoder),
        "session": s,
        "readingsCount": len(readings)
    })


@login_required(login_url=reverse_lazy("exhibitionInferenceApp_ns:login"))
@permission_required(
    "exhibitionInferenceApp.visualise_reading",
    raise_exception=True
)
def dataDefault(req: WSGIRequest) -> HttpResponse:
    if req.method != "GET":
        raise Http404("Must make a GET request!")
    readings: List[Reading] = utils.getAllReadings()
    return render(req, "exhibitionInferenceApp/data.html", context={
        "data": json.dumps(readings, cls=ReadingEncoder)})


##################
# LOGIN / LOGOUT #
##################

def login(req: WSGIRequest):
    if req.method != "GET":
        raise Http404("Must make a GET request!")

    if req.user.is_authenticated:
        # If already logged in, redirect to index
        return HttpResponseRedirect(reverse("exhibitionInferenceApp_ns:index"))
    return render(req, "exhibitionInferenceApp/login.html", context={})


def loginPost(req: WSGIRequest):
    if req.method != "POST":
        raise Http404("Must make a POST request!")

    username = req.POST["username"]
    password = req.POST["password"]

    user = authenticate(req, username=username, password=password)
    if user is not None:
        # actual logging in, and saving to internal sessions database
        authLogin(req, user)

        # if a ?next= was in the URL, redirect to that.
        # (adding ?next= is done by @login_required)
        # (try visiting /frontdesk/devices when logged out, then logging in, to see how this works)
        urlQueryNexts = parse_qs(urlparse(req.META["HTTP_REFERER"]).query)\
            .get("next", [None])
        if len(urlQueryNexts) == 1 and urlQueryNexts[0] is not None:
            next = urlQueryNexts[0]
            return redirect(next)
        return HttpResponseRedirect(reverse("exhibitionInferenceApp_ns:index"))
    else:
        messages.error(req, "Invalid login credentials.")
        # Redirect to same page (/login/?next=...) if ?next= is specified, otherwise go to default login page (/login/)
        return HttpResponseRedirect(req.META.get("HTTP_REFERER", reverse("exhibitionInferenceApp_ns:login")))


def logout(req: WSGIRequest):
    if req.method != "POST":
        raise Http404("Must make a POST request!")

    authLogout(req)
    return HttpResponseRedirect(reverse("exhibitionInferenceApp_ns:index"))


############
# HARDWARE #
############

@csrf_exempt
def submitReading(req: WSGIRequest) -> HttpResponse:
    def _xyzWithinBounds(x: float, y: float, z: float):
        bounds = utils.getMetadataXYZBounds()
        return bounds["X_LOWER_BOUND_METRES_INC"] <= x <= bounds["X_UPPER_BOUND_METRES_INC"] and \
            bounds["Y_LOWER_BOUND_METRES_INC"] <= y <= bounds["Y_UPPER_BOUND_METRES_INC"] and \
            bounds["Z_LOWER_BOUND_METRES_INC"] <= z <= bounds["Z_UPPER_BOUND_METRES_INC"]

    # WARNING: Potentially unsafe, particularly if POSTer has to be authenticated.
    # So far, our POSTers are not authenticated in any way, so CSRF protection is not necessary.
    print("Executed")
    if req.method != "POST":
        raise Http404("Must make a POST request!")

    try:
        data = json.loads(req.body)
    except (json.JSONDecodeError):
        return HttpResponseBadRequest("Submission not in valid JSON format!")

    try:
        x = float(data["x"])
        y = float(data["y"])
        z = float(data["z"])
        t = make_aware(datetime.fromtimestamp(float(data["t"])))
        hardwareId = str(data["hardwareId"])
        quality = int(data["quality"])

        print("t is {0}".format(t))
    except (KeyError, ValueError) as e:
        print("Error: {0}".format(e))
        return HttpResponseBadRequest("Invalid JSON received!")

    # get or create device associated with hardware id
    device: Device = utils.getOrCreateDeviceByHardwareId(hardwareId)

    # get the active session associated with the device
    s: Optional[Session] = utils.getActiveSessionIfExists(device=device)
    if not _xyzWithinBounds(x, y, z):  # location out of bounds
        # end session if one exists
        if s:
            utils.endSession(s)
        return HttpResponseBadRequest("Submission dropped: Location out of bounds.")
    if s:
        if utils.hasExpired(s, t):
            # session has expired, end it and make a new one
            utils.endSession(s)
            s = utils.createSession(device, t)
    else:
        # no sessions active, create one
        s = utils.createSession(device, t)

    try:
        utils.writeReading(
            x=x,
            y=y,
            z=z,
            t=t,
            session=s,
            quality=quality
        )
    except IntegrityError as e:

site/exhibitionInferenceSite/exhibitionInferenceApp/templates/exhibitionInferenceApp/base.html
<!-- A Django HTML Template used by all other .html files in this directory -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="{% static 'exhibitionInferenceApp/images/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">
    {% block additionalHead %}
    <!-- allows .html files that extend this html to include more stuff within this region -->
    {% endblock %}
    <title>Exhibition Inference</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid ms-1">
            <a class="navbar-brand" href="{% url 'exhibitionInferenceApp_ns:index' %}">Exhibition Inference</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                {% if user.is_authenticated %}
                <!-- Doable actions only shown to authenticated users -->
                <ul class="navbar-nav me-auto">
                    <li class="nav-item active">
                        <a class="nav-link {% block manageDevicesClass %}{% endblock %}"
                            href="{% url 'exhibitionInferenceApp_ns:frontdesk-device-select' %}">Manage Devices</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link {% block manageSessionsClass %}{% endblock %}"
                            href="{% url 'exhibitionInferenceApp_ns:frontdesk-session-select' %}">Manage Sessions</a>
                    </li>
                    {% if perms.exhibitionInferenceApp.visualise_reading %}
                    <li class="nav-item active">
                        <a class="nav-link {% block visualisationClass %}{% endblock %}"
                            href="{% url 'exhibitionInferenceApp_ns:visualisation-default' %}">Visualisation</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link {% block dataDump %}{% endblock %}"
                            href="{% url 'exhibitionInferenceApp_ns:data-default' %}">Data</a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <span class=" navbar-text fst-italic pe-2">
                        (Logged in as {{ user.username }})
                    </span>
                    {% endif %}
                    <li class="nav-item">
                        {% if not user.is_authenticated %}
                        <a class="nav-link {% block loginClass %}{% endblock %}"
                            href="{% url 'exhibitionInferenceApp_ns:login' %}">Login</a>
                        {% else %}
                        <button type="button" class="btn btn-link nav-link btn-no-focus" data-bs-toggle="modal"
                            data-bs-target="#logoutModal">
                            Logout
                        </button>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% if user.is_authenticated %}
    <!-- Logout modal only loaded if user is authenticated -->
    <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="logoutModalLabel">Confirm Logout</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Any unsaved changes will be lost.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <form action="{% url 'exhibitionInferenceApp_ns:logout' %}" method="post">
                        {% csrf_token %}
                        <div class="text-end">
                            <button type="submit" class="btn btn-primary">Logout</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <main role="main" class="container">
        {% block containerBody %}
        <!-- where main page's content goes -->
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

site/exhibitionInferenceSite/exhibitionInferenceApp/templates/exhibitionInferenceApp/deviceManage.html
{% extends "./base.html" %}

{% block manageDevicesClass %}active{% endblock %}

{% block containerBody %}
<div class="text-center w-75 mx-auto mb-3">
    <div class="card">
        <div class="card-header">
            <h1>{{ hardwareId }}</h1>
            {% if activeSessionOptional %}
            {% if not activeSessionOptional.device.metadata %}
            <span class="badge bg-danger rounded-pill ms-1">No metadata</span>
            {% endif %}
            <span class="badge bg-success rounded-pill ms-1">ACTIVE SESSION</span>
            {% else %}
            <span class="badge bg-secondary rounded-pill ms-1">IDLE</span>
            {% endif %}
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col text-start">
                    <h3>Current metadata:</h3>
                    {{ oldMetadata|default_if_none:"(empty)"|linebreaksbr }}
                </div>
                <div class="col text-start">
                    <h3>Active Session</h3>
                    {% if activeSessionOptional %}
                    Session ID:
                    <a href="{% url 'exhibitionInferenceApp_ns:frontdesk-session-manage' activeSessionOptional.pk %}">
                        {{ activeSessionOptional.pk }}</a><br />
                    Start Time: {{ activeSessionOptional.startTime|date:"r" }}<br />
                    Last Seen: {{ latestReading.t|date:"r" }}<br />
                    {% if session.endTime %}
                    End Time: {{ session.endTime|date:"r" }}<br />
                    {% else %}
                    End Time: (still ongoing)<br />
                    {% endif %}
                    {% else %}
                    <p>(none)</p>
                    {% endif %}

                    {% if perms.exhibitionInferenceApp.change_device %}
                    <h3 class="mt-3">Edit metadata:</h3>
                    <form action="{% url 'exhibitionInferenceApp_ns:frontdesk-device-manage-submit' hardwareId %}"
                        method="post">
                        {% csrf_token %}

                        {% if messages %}
                        {% for message in messages %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success" role="alert">{{ message }}</div>
                        {% endif %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger" role="alert">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        <textarea class="form-control" id="newMetadata" name="metadata"
                            placeholder="E.g. currently holding audioguide"
                            rows=15>{{ textboxMetadata|default_if_none:"" }}</textarea>
                        <button class="btn btn-primary w-100 mt-3" type="submit">Save Changes</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

site/exhibitionInferenceSite/exhibitionInferenceApp/templates/exhibitionInferenceApp/deviceSelect.html
{% extends "./base.html" %}

{% block manageDevicesClass %}active{% endblock %}

{% block containerBody %}
<div class="text-center">
    <h2>Device Select</h2>
    <div class="list-group w-50 mx-auto mb-3">
        {% for d, activeSession in devicesAndSessions %}
        <a href="{% url 'exhibitionInferenceApp_ns:frontdesk-device-manage' d.hardwareId %}"
            class="list-group-item d-flex align-items-center list-group-item-action">
            {{ d.hardwareId }}
            <div class="ms-auto">
                {% if activeSession %}
                {% if not activeSession.device.metadata %}
                <span class="badge bg-danger rounded-pill ms-1">No metadata</span>
                {% endif %}
                <span class="badge bg-success rounded-pill ms-1">ACTIVE SESSION</span>
                {% else %}
                <span class="badge bg-secondary rounded-pill ms-1">IDLE</span>
                {% endif %}
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

site/exhibitionInferenceSite/exhibitionInferenceApp/templates/exhibitionInferenceApp/login.html
{% extends "./base.html" %}

{% block loginClass %}active{% endblock %}

{% block containerBody %}
<div class="w-25 mx-auto">
    <form action="{% url 'exhibitionInferenceApp_ns:login-submit' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>
        {% if messages %}
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
        {% endfor %}
        {% endif %}
        <div class="text-end">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
    </form>
</div>
{% endblock %}

site/exhibitionInferenceSite/exhibitionInferenceApp/templates/exhibitionInferenceApp/sessionManage.html
{% extends "./base.html" %}

{% block manageSessionsClass %}active{% endblock %}

{% block containerBody %}
<div class="text-center w-75 mx-auto mb-3">
    <div class="card">
        <div class="card-header">
            <h1>Session {{ session.pk }}</h1>
            {% if not session.endTime and not session.device.metadata or session.endTime and not session.metadata %}
            <span class="badge bg-danger rounded-pill ms-1">No metadata</span>
            {% endif %}
            {% if session.endTime %}
            <span class="badge bg-primary rounded-pill ms-1">ENDED</span>
            {% else %}
            <span class="badge bg-success rounded-pill ms-1">IN PROGRESS</span>
            {% endif %}
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col text-start">
                    <h3>Current metadata:</h3>
                    {% if session.endTime %}
                    {{ oldMetadata|default_if_none:"(empty)"|linebreaksbr }}
                    {% else %}
                    {{ session.device.metadata|default_if_none:"(empty)"|linebreaksbr }}
                    {% endif %}
                </div>
                <div class="col text-start">
                    <h3>Details</h3>
                    {% if session %}
                    Device ID: {{ session.device.pk }}<br />
                    Start Time: {{ session.startTime|date:"r" }}<br />
                    Last Seen: {{ latestReading.t|date:"r" }}<br />
                    {% if session.endTime %}
                    End Time: {{ session.endTime|date:"r" }}<br />
                    {% else %}
                    End Time: (still ongoing)<br />
                    {% endif %}
                    {% else %}
                    <p>(none)</p>
                    {% endif %}

                    {% if perms.exhibitionInferenceApp.change_device %}
                    <h3 class="mt-3">Edit metadata:</h3>
                    {% if not session.endTime %}
                    <a href="{% url 'exhibitionInferenceApp_ns:frontdesk-device-manage' session.device.pk %}">
                        Manage Device: {{ session.device.pk }}</a>
                    {% else %}
                    <form action="{% url 'exhibitionInferenceApp_ns:frontdesk-session-manage-submit' session.pk %}"
                        method="post">
                        {% csrf_token %}

                        {% if messages %}
                        {% for message in messages %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success" role="alert">{{ message }}</div>
                        {% endif %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger" role="alert">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        <textarea class="form-control" id="newMetadata" name="metadata"
                            placeholder="E.g. currently holding audioguide"
                            rows=15>{{ textboxMetadata|default_if_none:"" }}</textarea>
                        <button class="btn btn-primary w-100 mt-3" type="submit">Save Changes</button>
                    </form>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}